### ISSUE TITLE
bugs when install FATE

### ISSUE THREAD

**Issue by lytofd** [WeBankFinTech/FATE#266]
There are three questions summaried when install FATE framework(master branch).
1,  install_py3.sh
     pip install -r ./pip-dependencies/requirements.txt -f ./pip-dependencies  --no-index
     errors occures at this line,it seems that it could not find the specific version,when we delete  --no-index,errors disappears.
2,  install_mysql.sh
     this script installs mysql into the path "/data/projects/common/mysql/mysql-8.0/",but in next step ,FATE want user to change password,  command could be :
      /data/projects/common/mysql/mysql-8.0.13/bin/mysql -uroot -p -S/data/projects/common/mysql/mysql-8.0.13/mysql.sock
      but the directory mysql-8.0.13  does  not exists.
3,  After installing the mysql, user should change the password,but the password is  difficult to find, it is shown in the  process of installing,such as 
     [Note] [MY-010454] [Server] A temporary password is generated for root@localhost: ******
     l hope  the hint could be more friendly.
     Thanks.

**Comment by paulbaogang** [comment]
@lytofd Hello, thank you for your question.
The answers for your three questions are as follows:
1. When using pip install to download Python dependent packages, "-no-index" means that you specify the form of offline installation of downloaded packages. If you install online, you do not need to use the way in install_py3.sh. Of course, it is feasible to delete "-no-index" manually, but when installing offline, "-no-index" It is necessary.
2. The MySQL path is needed to match the actual installation path, such as "/ data/projects/common/mysql/mysql-8.0", so the command can be / data/projects/common/common/mysql/common/mysql-8.0/mysql-8.0/bin/mysql-uroot-p-s/data/projects/common/mysql/mysql-8.0/mysql.sock. There is a slight deviation in the path of the example.
3. Finding passwords in Mysql's installation log is a bit of a hassle, but we can't do much because changing passwords requires you to customize them, but we'll still try to make the installation more automated in the script that takes MySQL into account.
Thank you for your detailed questions.
