### ISSUE TITLE
How to interpret the process and performance for guest and host?

### ISSUE THREAD

**Issue by crownpku** [WeBankFinTech/FATE#28]
I'm trying to interpret the results, understand the training and evaluation process and the loss/accuracy for each of the guest and the host for each round.

For example I run the logistic regression standalone version, and get all the logs: homo_lr_guest.log, homo_lr_host.log and homo_lr_arbiter.log.

Where should I look for the performance for each round for each of the guest? And the host model performance? Is there a good way to interpret the results and get the metrics of the whole process (model distributing, guest training performance, model encryption, model merging, host training performance etc.)

Thanks!

**Comment by tanmc123** [comment]
Thanks for you questions.
1. Where should I look for the performance for each round for each of the guest?
The performance of each round is not avaiable yet. It will be a enhancement in future versions. 

2. And the host model performance?
Please be clearified that, there is no host performance vs. guest performance. The performance of the model is contributed by both parties. Therefore, only one performance will be available.  Besides, for homo-lr, if you use encryption method for host (which is set by default), there is no way to get lost in host end.

**Comment by crownpku** [comment]
Thanks @tanmc123 .

By host performance for each round, I mean the performance of the merged model, which will be the initial model for each of the guest for the next round. I'm checking this because I expect such merged model will perform better than the separate guest models for each round.

Ideally it will be best if we can have a monitoring method (either screen printout/logs or a UI visualization) to see the performance for all the parties while training. Something like [here](https://turbofan.fastforwardlabs.com/). Not sure if this is a priority but this can be important for illustrating and explaining FL for PoCs.

**Comment by tanmc123** [comment]
Thanks @crownpku 
For final model, a performance report will be shown in guest end. This is already the performance of the merged model. It is because the model in guest part is unencrypted, so that this performance report is shown in guest end. 

As for performance for each round, I'm afraid it is not avaible yet. There will be some loss report shown in guest log, which can be used to check out if any improvement made. But, right, there is no way to compare single guest model with merged model at this point. I am pretty sure, it will be shown up in the future. 

As for the plan of this feature as well as the monitoring method, hopefully, it could be finished by the next 2 releases.
