### ISSUE TITLE
About the “Proxy” Module

### ISSUE THREAD

**Issue by YangjieZhou** [WeBankFinTech/FATE#283]
Hi,

1.  If I can set only one ip address serving as the "proxy" node for two or even more parties? 

Thanks a lot!!!

**Comment by YangjieZhou** [comment]
Add:

I know different proxy module in different party has different ip address. And the same port "9370" can have a conflict for serving. Can I change the port so that each party can have just one exchangeip address?

**Comment by zzzcq** [comment]
@YangjieZhou 

> Hi,
> 
> 1. If I can set only one ip address serving as the "proxy" node for two or even more parties?
> 
> Thanks a lot!!!

The answer is yes.Each of module can set only one ip address by changing port.By the other hand, multiple "proxy" can use only one exchangeip address.

**Comment by YangjieZhou** [comment]
@zzzcq 

In that case, what does the exchangeip address work for?

**Comment by zengjice** [comment]
Hi yangjie,
Proxy and exchange are similar to soft routes in order to build a federated network. If the two parties do not have network isolation, they can be simply deployed. For example, only one proxy can be used, and the routing information of the two parties is configured on the route config. The serving is also on-demand, has nothing to do with the proxy, and should not conflict. 
Thanks.
