### ISSUE TITLE
Error: No such container:docker

### ISSUE THREAD

**Issue by hubuwx** [WeBankFinTech/FATE#294]
使用docker安装standalone版本的时候，执行第三步出现如题的错误，请问各位有没有遇到过啊？你们是怎么解决的呢？

**Comment by paulbaogang** [comment]
Can you see the build of docker images? Execute the command :docker images.If it exists, execute ps -a to see if the container exists or not?

**Comment by wangxuhubu** [comment]
execute the command : docker images  return some anonymous repository  image.
and when i execute the command: docker run -t -d fate/standalone , the result is error : Unable to find the image "fate/standalone:latest" locally.
by the way, the first command sh ,there are some red line:
`debconf : delaying package configuration,since apt-utils is not installed `( but i have installed apt-utils)
```
E: Unable to locate package libmpfr4
E: Unable to locate package libmpfr4-dbg
```

**Comment by paulbaogang** [comment]
this is dockfile:
FROM python:3.6

WORKDIR /fate

COPY . /fate

RUN rm /bin/sh && ln -sf /bin/bash /bin/sh

RUN tar -xf fate.tar

RUN rm fate.tar

RUN apt-get update && apt-get install libgmp3-dev -y && apt-get install -y libmpfr-dev libmpfr-doc libmpfr4 libmpfr4-dbg && apt-get install libmpc-dev -y

RUN pip install -r requirements.txt

ENV PYTHONPATH /fate

**Comment by paulbaogang** [comment]
Confirm whether the environment can access the external network? The docker host machine can execute:
RUN apt-get update && apt-get install libgmp3-dev -y && apt-get install -y libmpfr-dev libmpfr-doc libmpfr4 libmpfr4-dbg && apt-get install libmpc-dev -y

**Comment by paulbaogang** [comment]
Should be dependent package can not be installed, you need to check the network or yum source.

**Comment by wangxuhubu** [comment]
i'am sure the network is fine ,and the dockerfile is just like yours，but cannot locate the package libmpfr4 and libmpfr4-dbg. like the ISSUE No.51

**Comment by paulbaogang** [comment]
After testing, ubuntu official website does not support the automatic installation of libmpfr4 package, instead of libmpfr6, you may need to modify the docker/standalone/Dockerfile: 

RUN apt-get update && apt-get install libgmp3-dev -y && apt-get Install -y libmpfr-dev libmpfr-doc libmpfr4 libmpfr4-dbg && apt-get install libmpc-dev -y

changed to

RUN apt-get update && apt-get install libgmp3-dev -y && apt-get install -y libmpfr-dev libmpfr-doc libmpfr6 && apt-get install libmpc-dev -y

We will modify the instructions in the follow-up, you can try it first, thank you.

**Comment by hubuwx** [comment]
Thanks a lot, and I’ll try it later. 
By the way, I have changed the dockerfile mentioned in issue 51 (use wget command to install libmpfr4 and libmpfr4-dbg from Debian website) , it worked out.
I have another question about the results after running the logistic regression example, I cannot find the log directory as the README mentioned, could you tell me the other way I can get the log ,thank you.

**Comment by Song-xx** [comment]
I am not very sure about my solution,you can try if you have no better way.
---------------------------------------------------------------------------------------------------
I have the same error when execute:
`sudo docker exec -t -i ${CONTAINER_ID} bash`
You can try(examine docker and docker-compose first):
`sudo docker run -t -i ${CONTAINER_ID} bash`
it seems because 'exec' use a exist docker,'run' is to open a new one.

**Comment by Song-xx** [comment]
I come across this problem and solved it,may it help you.
(1) ensure you successfully download the tar.gz file;
(2) for line in the README.md
`CONTAINER_ID='docker ps -aqf "name=fate_python"'`
use 
`docker ps -aqf "name=fate_python"`
to get the Container ID by hand(for me it is "d4a95de0b4dd"),and assign it to CONTAINER_ID,such as 
`CONTAINER_ID="d4a95de0b4dd"`
(3)then  you can do as the tutorial,
`docker exec -t -i ${CONTAINER_ID} bash`

actually  I don't know why but it works for me.

Gook Luck!
